Repository moonstream-to/api, pull requests merged in 2022-05, with the labels that each got.

#599 Add migration for create index for speed up queries.
  db/alembic/versions/5f5b8f19570f_added_index_for_address_type_and_name_.py
  db/moonstreamdb/models.py
Labels: db

#603 xDai node deployment
  nodes/deploy/xdai/deploy.bash
  nodes/deploy/xdai/node-status.service
  nodes/deploy/xdai/xdai.service
  nodes/server/cmd/routes.go
  nodes/server/cmd/server.go
Labels: deployment

#605 Cli config file for node list setup
  nodes/.gitignore
  nodes/deploy/deploy.bash
  nodes/deploy/node-balancer-config.txt
  nodes/deploy/node-balancer.service
  nodes/node_balancer/cmd/cli.go
  nodes/node_balancer/cmd/clients.go
  nodes/node_balancer/cmd/routes.go
  nodes/node_balancer/cmd/server.go
  nodes/node_balancer/configs/settings.go
  nodes/node_balancer/configs/version.go
  nodes/node_balancer/dev.sh
  nodes/node_balancer/main.go
Labels: deployment, infra

#607 Removed all refs
  db/scm.nix
Labels: db

#610 Auto deploy of moonworm cu mainnet crawler
  crawlers/deploy/deploy-moonworm-cu.bash
  crawlers/deploy/moonworm-unicorns-mainnet.service
Labels: crawlers

#567 Crawlers access id to work with nodebalancer
  crawlers/deploy/ethereum-missing.service
  crawlers/deploy/ethereum-synchronize.service
  crawlers/deploy/ethereum-trending.service
  crawlers/deploy/ethereum-txpool.service
  crawlers/deploy/polygon-missing.service
  crawlers/deploy/polygon-moonworm-crawler.service
  crawlers/deploy/polygon-statistics.service
  crawlers/deploy/polygon-synchronize.service
  crawlers/deploy/polygon-txpool.service
  crawlers/mooncrawl/mooncrawl/api.py
  crawlers/mooncrawl/mooncrawl/blockchain.py
  crawlers/mooncrawl/mooncrawl/contract/cli.py
  crawlers/mooncrawl/mooncrawl/crawler.py
  crawlers/mooncrawl/mooncrawl/identity.py
  crawlers/mooncrawl/mooncrawl/moonworm_crawler/cli.py
  crawlers/mooncrawl/mooncrawl/moonworm_crawler/continuous_crawler.py
  crawlers/mooncrawl/mooncrawl/nft/cli.py
  crawlers/mooncrawl/mooncrawl/settings.py
  crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py
  crawlers/mooncrawl/mooncrawl/version.py
  crawlers/mooncrawl/sample.env
  crawlers/txpool/cmd/txpool.go
  crawlers/txpool/dev.sh
  crawlers/txpool/sample.env
Labels: crawlers

#559 Auth workflow for balancer
  .gitignore
  crawlers/deploy/moonworm-unicorns-mainnet.service
  nodes/node_balancer/README.md
  nodes/node_balancer/cmd/balancer.go
  nodes/node_balancer/cmd/blockchain.go
  nodes/node_balancer/cmd/cli.go
  nodes/node_balancer/cmd/clients.go
  nodes/node_balancer/cmd/data.go
  nodes/node_balancer/cmd/db.go
  nodes/node_balancer/cmd/middleware.go
  nodes/node_balancer/cmd/routes.go
  nodes/node_balancer/cmd/server.go
  nodes/node_balancer/configs/settings.go
  nodes/node_balancer/configs/version.go
  nodes/node_balancer/go.mod
  nodes/node_balancer/go.sum
  nodes/node_balancer/sample.env
Labels: infra

#613 xdai db model
  db/alembic/versions/2fa541f6f6fc_xdai_model.py
  db/moonstreamdb/models.py
  db/moonstreamdb/version.py
Labels: db

#615 XDai crawlers
  crawlers/deploy/deploy.bash
  crawlers/deploy/xdai-missing.service
  crawlers/deploy/xdai-missing.timer
  crawlers/deploy/xdai-synchronize.service
  crawlers/mooncrawl/mooncrawl/blockchain.py
  crawlers/mooncrawl/mooncrawl/data.py
  crawlers/mooncrawl/mooncrawl/settings.py
Labels: crawlers

#619 XDai database blockchain update to support XDai
  db/moonstreamdb/blockchain.py
  db/moonstreamdb/version.py
Labels: db

#616 XDai subscriptions
  backend/moonstreamapi/actions.py
  backend/moonstreamapi/admin/cli.py
  backend/moonstreamapi/admin/subscription_types.py
  backend/moonstreamapi/providers/__init__.py
  backend/moonstreamapi/providers/moonworm_provider.py
  backend/moonstreamapi/providers/transactions.py
  backend/moonstreamapi/routes/dashboards.py
  backend/moonstreamapi/version.py
  backend/setup.py
  crawlers/deploy/deploy.bash
  crawlers/deploy/xdai-statistics.service
  crawlers/deploy/xdai-statistics.timer
  crawlers/mooncrawl/mooncrawl/generic_crawler/cli.py
  crawlers/mooncrawl/mooncrawl/moonworm_crawler/cli.py
  crawlers/mooncrawl/mooncrawl/moonworm_crawler/continuous_crawler.py
  crawlers/mooncrawl/mooncrawl/moonworm_crawler/crawler.py
  crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py
  crawlers/mooncrawl/mooncrawl/version.py
  crawlers/mooncrawl/setup.py
Labels: backend, crawlers

#621 XDai moonworm crawler service
  crawlers/deploy/deploy.bash
  crawlers/deploy/xdai-moonworm-crawler.service
Labels: crawlers, infra

#622 Using replica read only to get subscription events
  backend/moonstreamapi/routes/streams.py
Labels: backend
